# Generated by Django 5.0.3 on 2024-03-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMaterial',
            new_name='ProductMaterialModel',
        ),
    ]
